on:
  push:
    branches:
      - main

jobs:
# run all unit tests.
  run-tests:
    runs-on: ubuntu-latest
    steps:
      # Check out the pushed code
      - name: Check out the source code
        uses: actions/checkout@v2

      # Install Go.
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17"
      - name: Print Go version
        run: go version

      # Test Go
      - name: Go Env Setup
        run: go env -w GO111MODULE=off

      # Build (Added after GOROOT error)
      #- name: Build
      #  run: go build -v ./...

      - uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

      # Run unit tests.
      - name: Run  unit tests.
        run: go test -v ./...
