on:
  push:
    branches:
      - main

jobs:
# run all unit tests.
  run-tests:
    runs-on: ubuntu-latest
    steps:
      # Check out the pushed code
      - name: Check out the source code
        uses: actions/checkout@v2

      # Install Go.
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17"

      - name: Print Go version
        run: go version

      # Test Go
      - name: Go Env Setup
        run: go env -w GO111MODULE=on

      # Run unit tests. (working directory to be changed after adding new packages)
      - name: Run  unit tests.
        working-directory: ./pkg/stringOps
        run: go test -v

